Synchronize the dabao1955 repository code

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -40,7 +40,7 @@ inputs:
   ksu:
     required: false
     default: false
-  rekernel:
+  zram:
     required: false
     default: false
   ksu-version:
@@ -345,9 +345,22 @@ runs:
             echo "::endgroup::"
         fi
 
-        if [ "${{ inputs.rekernel }}" == "true" ]; then
-            echo "::group::Initializing Re-Kernel"
-            curl -SsL https://github.com/dabao1955/kernel_build_action/raw/main/rekernel/patch.sh | bash
+        if [[ "${{ inputs.ksu-url }}" == *"SukiSU-Ultra"* ]]; then
+            echo -e "CONFIG_KPM=y\nCONFIG_KSU_MANUAL_HOOK=y\nCONFIG_KALLSYMS=y\nCONFIG_KALLSYMS_ALL=y" >> arch/${{ inputs.arch }}/configs/${{ inputs.config }}
+            sed -i 's/#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 9, 0))/#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 14, 0))/' KernelSU/kernel/kpm/super_access.c
+        fi
+
+        if [ "${{ inputs.zram }}" == "true" ]; then
+            echo "::group::Initializing Zram"
+            #aria2c https://github.com/Fyj69/patch/raw/main/rekernel/rekernel-4.9.patch && patch -p1 -F 3 < rekernel-4.9.patch
+            git clone https://github.com/ShirkNeko/SukiSU_patch.git
+            aria2c https://github.com/Fyj69/patch/raw/main/kernelsu/lz.sh && bash lz.sh arch/${{ inputs.arch }}/configs/${{ inputs.config }}
+            aria2c https://github.com/Fyj69/patch/raw/main/zram_4.9/lz.patch && patch -p1 -F 3 < lz.patch
+            cp -r ./SukiSU_patch/other/zram/lz4k/include/linux/* ./include/linux/
+            cp -r ./SukiSU_patch/other/zram/lz4k/lib/* ./lib/
+            cp -r ./SukiSU_patch/other/zram/lz4k/crypto/* ./crypto/
+            cp -r ./SukiSU_patch/other/zram/lz4k_oplus ./lib/
+            sed -i 's/CONFIG_ZRAM_DEFAULT_COMP_ALGORITHM="zstd"/CONFIG_ZRAM_DEFAULT_COMP_ALGORITHM="lz4kd"/' arch/${{ inputs.arch }}/configs/${{ inputs.config }}
             echo "::endgroup::"
         fi
 
@@ -474,6 +487,24 @@ runs:
         echo "::endgroup::"
 
         unset CMD_PATH CMD_CC CMD_CLANG_TRIPLE CMD_CROSS_COMPILE CMD_CROSS_COMPILE_ARM32 USE_CCACHE CLANG_PATH HOMES KVER SWAP_FILE SUBLEVEL PATCHLEVEL VERSION GCC_DIR FILE FILE_NAME MATCHED_DIR FOLDER FOLDER_NAME GCC64 GCC32 NEED_GCC AOSP_CLANG_URL OTHER_CLANG_URL AOSP_GCC64_URL AOSP_GCC32_URL AOSP_GCC_BRANCH OTHER_GCC64_URL OTHER_GCC32_URL make_args
+
+        if [ -d KernelSU/kernel/kpm ] || [ -d KernelSU-Next/kernel/kpm ]; then
+            echo "::group:: Patch SukiSU Ultra KPM"
+            cd out/arch/${{ inputs.arch }}/boot
+            aria2c https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux -o patch
+            chmod 777 patch
+            ./patch
+            if [ $? -eq 0 ]; then
+              rm -f Image*
+              cp dts/qcom/*.dtb .
+              mv oImage Image
+              gzip -k Image Image.gz
+              cat Image.gz *.dtb > Image.gz-dtb && cd -
+              echo "Image file patching completed"
+            else
+              echo "KPM patching failed, using the original Image"
+            fi
+        fi
 
         if [ "${{ inputs.anykernel3 }}" == "false" ]; then
             echo "::group::Packaging boot.img"
